#!/usr/bin/python3
#  base.py
#  DevWambugu
'''This class is be the “base” of all other classes in this project.
The goal of it is to manage id attribute in all your future classes
and to avoid duplicating the same code (by extension, same bugs)
'''
from models.base import Base


class Rectangle(Base):
    '''This class inherits from the Base class
    It sets Private instance attributes,
    each with its own public getter and setter
    '''
    def __init__(self, width, height, x=0, y=0, id=None)
    '''start by calling the super class'''
        super().__init__(id)
        self.width = width
        self.height = height
        self.x = x
        self.y = y
    
    @property
    def width(self):
    '''retrive width property as a private
    attribute'''
        return self.__width

    @width.setter
    def width(self, value)
    '''assign value to width'''
        self.__width = value

    @property
    def height(self):
    '''retrieve height property as a private
    attribute'''
        return self.__height

    @height.setter
    def height(self, value)
    '''assign value to width'''
        self.__height = value

    @property
    def x(self)
    '''retrieves x property as a
    private attribute'''
        return self.__x

    @x.setter
    def x(self, value)
    '''assigns value to x'''
        self.__x = value

    @property
    def y(self)
    '''retrieves y attribue a s a private attribute'''
        return self.__y

    @y.setter
    def y(self, value)
    '''sets the private aattribute y'''
        self.__y = value
