#!/usr/bin/python3
'''
script that takes in a URL, sends a request to the URL
and displays the value of the X-Request-Id
variable found in the header of the response.
'''
import urllib.request
import sys

if __name__ == "__main__":
    url = sys.argv[1]
    req_object = urllib.request.Request(url)
    with urllib.request.urlopen(req_object) as response:
        if 'X-Request-Id' in response.headers:
            x_request_id = response.headers['X-Request-Id']
	    print(x_request_id)
        else:
            pass
