#!/usr/bin/python3
# 0-rectangle.py
# DevWambugu
"""Define a class rectangle."""


class Rectangle:
    """Define a class rectangle
    the attributes for this class have
    not been defined
    """

    pass
